Fire MQ Rework
OoTMM/OoTMM pull request #798
Opened 2024-11-16 18:38 UTC by Joshua8600

2024-12-25 00:09 UTC, XenoWars requested changes
This one's a big one.

2024-12-25 00:09 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && can_collect_distance"
Could destroy it with explosives/blast mask, a jump slash (but not with hammer), or some other ranged weapon then use climb anywhere.

2024-12-25 00:09 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_TOWER_AFTER_FLARE_DANCER_HOOKSHOT_TARGETS: "has_weapon || has_bombs || can_use_mask_blast || has_bombchu || can_use_bow || can_use_slingshot || can_hookshot || can_use_sticks || can_hamme
They put one higher up, but it doesnt do anything lol. Seems it can only be useful for getting back after dropping down with the pillar.

2025-01-10 18:41 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Lower Lobby": "true"
Ehh, it's more for consistency than anything. Some dungeons have that "DUNGEON NAME" stub region and others don't when I first started the reworks. So I added them to all for consistency.

Also, it might be worth having if we get both regular and MQ dungeon varieties in the same seed in the future.

2025-01-10 18:45 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_1ST_GORON_LIKELIKE: "can_damage && soul_like_like"
Added.

2025-01-10 18:46 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 1F Lava Bridge Room Main": "can_hammer && has_tunic_goron"
Added.

2025-01-10 18:58 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (hookshot_anywhere || climb_anywhere || event(FIRE_MQ_PRE_BOSS_PILLAR))"
Changed.

2025-01-10 19:12 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (is_adult || climb_anywhere || hookshot_anywhere)"
I didn't even think about this; you're right! I did this section way before I did the crate logic.

Fixed.

2025-01-10 19:15 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_PRE_BOSS_TORCHES: "(has_tunic_goron || (is_child && has_tunic_goron_strict)) && has_fire && (can_use_bow || has_hover_boots)"
This confuses me. Do you want me to just replace the event line with what you wrote?

2025-01-10 19:17 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple Pre-Boss Room Tall Ledge Top Large Crate": "has_tunic_goron || (is_child && has_tunic_goron_strict)" #Child can reach this by using the middle crate as a platform.
Fixed, and also added tunic to the pots.

2025-01-10 19:18 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_HAMMER_LOOP_FLARE_DANCER_CLEAR: "soul_enemy(SOUL_ENEMY_FLARE_DANCER) && (has_bombs || can_use_mask_blast || can_hammer || can_hookshot) && has_weapon"
I don't understand.

2025-01-10 19:22 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Lava Bridge Room South Side Ledge": "has_tunic_goron && can_hookshot" #Found a glitch too with climb anywhere and damage boosting through the moving platform.
Added.

2025-01-10 19:22 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Rising Block Room": "has_tunic_goron_strict && small_keys_fire_mq(2)"
I disagree with that.

2025-01-10 19:24 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_LAVA_BRIDGE_ROOM_TORCHES: "has_fire" #Might need to separate intwo two events when action shuffle happens.
Climbing/Jumping (action) and using din's, vs Fire Arrows only from a distance.

2025-01-10 19:26 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS 1f Lava Room": "gs && can_hammer && can_damage_skull"
Removed it.

2025-01-10 19:28 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Rising Block Room": "has_tunic_goron_strict && small_keys_fire_mq(2)"
Fixed.

2025-01-10 19:28 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 1F Lava Bridge Room Main": "has_tunic_goron_strict && small_keys_fire_mq(2)"
Fixed.

2025-01-10 19:33 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Cell Corner": "has_tunic_goron && (can_hookshot || has_hover_boots || climb_anywhere)"
Changed.

2025-01-10 19:34 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_HAMMER_LOOP_KNUCKLE_CLEAR: "soul_iron_knuckle && has_weapon"
This will be changed when we have the enemy defeat macros. I'd rather just leave this as-is for now.

2025-01-10 19:44 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper": "(event(FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH) && can_hookshot) || climb_anywhere || hookshot_anywhere"
Added the TODO

2025-01-10 19:46 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Rusty Switch Behind Bombable Wall": "has_explosives" #Separated for enemy drop rando and the skulwalltula
Does it hurt leaving this in for now?

2025-01-10 19:50 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Tower Area Above Maze Room": "can_longshot || (is_adult && hookshot_anywhere) || climb_anywhere" #Can be used to get to upper maze room without the rusty switch.
Changed.

2025-01-10 19:52 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH: "can_hammer"
Acknowledged. Marking this as resolved so we can discuss in the earlier one.

2025-01-10 19:53 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH: "trick(OOT_HAMMER_WALLS) && can_hammer"
TBH i don't even know what trick you're referring to. I put in the TODO but I don't understand what you mean.

2025-01-10 19:53 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon"
Can you write what you want me to change it to?

2025-01-10 19:56 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Burning Block": "gs && ((event(FIRE_MQ_EAST_TOWER_TOP_HOOKSHOT_TARGETS) && can_hookshot) || hookshot_anywhere || climb_anywhere)"
Added a TODO

2025-01-10 19:58 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 3F Lava Room Cage Area": "(has_tunic_goron && (is_adult || hookshot_anywhere || climb_anywhere)) || (has_tunic_goron_strict && can_hookshot)" #Adult can make an angled jump from the
You sure? I couldn't do it.

2025-01-10 20:00 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Inside Maze Narrow Paths Room": "has_tunic_goron_strict || (has_tunic_goron && is_adult)" #Adult just gets through it faster.
Changed.

2025-01-10 20:02 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 3F Lava Room Ledge Before Fire Walls Hallway": "(has_tunic_goron && is_adult) || (has_tunic_goron_strict && (can_hookshot || climb_anywhere))"
Changed.

2025-01-10 20:03 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_3F_LAVA_ROOM_TORCHES: "event(FIRE_MQ_3F_LAVA_ROOM_BLUE_SWITCH) && can_use_bow" #I could not get fire arrows to hit; maybe it works though.
what do i change it to?

2025-01-10 20:04 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple Pot Grids Above Lava 2": "has_tunic_goron_strict"
Changed.

2025-01-10 20:15 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple 3F Lava Room Near Cage Small Crate 2": "has_tunic_goron_strict && (is_adult || can_hookshot || climb_anywhere)"
Changed, also added TODO

2025-01-10 20:22 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_FLARE_DANCER_AFTER_FIRE_WALLS: "soul_enemy(SOUL_ENEMY_FLARE_DANCER) && (has_bombs || can_use_mask_blast || can_hammer || can_hookshot) && has_weapon"
Still don't quite understand.

2025-01-10 20:23 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple Flare Dancer Key": "event(FIRE_MQ_FLARE_DANCER_AFTER_FIRE_WALLS)"
Added the TODO

2025-01-10 20:27 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_TOWER_AFTER_FLARE_DANCER_CRYSTAL_SWITCH_FROM_BELOW: "event(FIRE_MQ_TOWER_TOP_HAMMER_SWITCH_BEFORE_STAIRCASE) && (has_ranged_weapon || has_bombchu)"
Different requirements depending on where you are.

2025-01-10 20:28 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && can_collect_distance"
What should it be changed to?

2025-01-10 20:29 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_TOWER_AFTER_FLARE_DANCER_HOOKSHOT_TARGETS: "has_weapon || has_bombs || can_use_mask_blast || has_bombchu || can_use_bow || can_use_slingshot || can_hookshot || can_use_sticks || can_hamme
lol.

2025-01-10 20:30 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon && (can_hookshot || climb_anywhere)" #You can get here to get to Upper Maze without the rusty switch.
what should it be changed to?

2025-01-10 20:32 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Fire Walls Room High Area After Staircase": "event(FIRE_MQ_HIGH_LEDGE_AFTER_STAIRCASE_PILLAR) && longshot_anywhere"
Added a TODO

2025-01-10 20:33 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Fire Walls Room Pillar Side": "event(FIRE_MQ_HIGH_LEDGE_AFTER_STAIRCASE_PILLAR)"
I can't envision this at the moment. Let's circle around to this after the rest.

2025-01-11 02:12 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_TOWER_AFTER_FLARE_DANCER_CRYSTAL_SWITCH_FROM_BELOW: "event(FIRE_MQ_TOWER_TOP_HAMMER_SWITCH_BEFORE_STAIRCASE) && (has_ranged_weapon || has_bombchu)"
That doesn't really matter. You need hook regardless if you dont have climb anywhere on, and its only use is to get back up from here anyway. Different requirements doesn't mean it needs to be a different event.

2025-01-11 02:15 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && can_collect_distance"
```suggestion
    "MQ Fire Temple GS Topmost": "gs && (can_collect_distance || ((has_explosives || can_use_mask_blast || has_weapon || has_ranged_weapon) && climb_anywhere))"
```

2025-01-11 02:30 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_PRE_BOSS_TORCHES: "(has_tunic_goron || (is_child && has_tunic_goron_strict)) && has_fire && (can_use_bow || has_hover_boots)"
Yes, change the event to this:

```suggestion
    FIRE_MQ_PRE_BOSS_TORCHES: "(has_tunic_goron && can_use_din && (is_adult || can_longshot || has_hover_boots || can_use_bow || hookshot_anywhere || climb_anywhere)) || (has_fire_arrows && ((has_goron_tunic_strict && is_child) || (has_goron_tunic && (can_longshot || hookshot_anywhere || (has_hover_boots && (is_adult || climb_anywhere))))))"
```

Also, the event can be added to the Entrance Side as well with just "has_tunic_goron && has_fire && can_use_bow" since as Grandma reminded me you can shoot the upper torch through the crate from there. Adding any other possibilities would just give you access from this corner.

2025-01-11 02:32 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_HAMMER_LOOP_FLARE_DANCER_CLEAR: "soul_enemy(SOUL_ENEMY_FLARE_DANCER) && (has_bombs || can_use_mask_blast || can_hammer || can_hookshot) && has_weapon"
at the last bit where it's just has_weapon. You can defeat him with sticks or hammer too, not just swords. And Bombchu can stun him/knock him out of the flames. Nothing fancy, it just blows up on contact.

2025-01-11 02:34 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_LAVA_BRIDGE_ROOM_TORCHES: "has_fire" #Might need to separate intwo two events when action shuffle happens.
Is jumping even going to be an action? Either way it's irrelevant right now.

2025-01-11 02:36 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon && (can_hookshot || climb_anywhere)" #You can get here to get to Upper Maze without the rusty switch.
```suggestion
    "Fire Temple Maze Room Upper Switch Cage Alcove": "can_hookshot || (climb_anywhere && (has_ranged_weapon || has_explosives || can_use_mask_blast))" #You can get here to get to Upper Maze without the rusty switch.
```

2025-01-11 02:39 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH: "trick(OOT_HAMMER_WALLS) && can_hammer"
the.. hammer through walls one? on the line that was responded to?

2025-01-11 02:46 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon"
```suggestion
    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon || has_explosives || can_use_mask_blast || can_jump_slash || (has_spin_upgrade && has_magic && (can_use_sword_master || can_use_sword_razor || can_use_sword_biggoron))"
```

2025-01-11 02:48 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 3F Lava Room Cage Area": "(has_tunic_goron && (is_adult || hookshot_anywhere || climb_anywhere)) || (has_tunic_goron_strict && can_hookshot)" #Adult can make an angled jump from the
You just walk up to it and climb up, simple as that.

2025-01-11 02:50 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_3F_LAVA_ROOM_TORCHES: "event(FIRE_MQ_3F_LAVA_ROOM_BLUE_SWITCH) && can_use_bow" #I could not get fire arrows to hit; maybe it works though.
```suggestion
    FIRE_MQ_3F_LAVA_ROOM_TORCHES: "(event(FIRE_MQ_3F_LAVA_ROOM_BLUE_SWITCH) && can_use_bow) || can_use_fire_arrow" #I could not get fire arrows to hit; maybe it works though.
```

2025-01-11 02:56 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Fire Walls Middle Hallway Upper": "true"
Since it's part of the thing you said we will circle back to, we will leave it for now.

2025-01-11 03:20 UTC, XenoWars requested changes

2025-01-11 03:20 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss": "has_tunic_goron && ((event(FIRE_MQ_PRE_BOSS_PILLAR) && has_hover_boots) || hookshot_anywhere || climb_anywhere)"
Why did you remove adult from this?

2025-01-11 03:20 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (climb_anywhere || hookshot_anywhere)"
Why did you remove adult from this? And shouldnt it be just the tunic anyway?

2025-01-11 03:20 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS 1f Lava Room": "gs && can_damage_skull"
Removed the wrong thing. Add hammer back, remove damage.

2025-01-12 17:44 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_PRE_BOSS_TORCHES: "(has_tunic_goron || (is_child && has_tunic_goron_strict)) && has_fire && (can_use_bow || has_hover_boots)"
I think shooting the torch through the crate should be a trick. I will add, but comment out the event with a TODO.

2025-01-12 17:47 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_HAMMER_LOOP_FLARE_DANCER_CLEAR: "soul_enemy(SOUL_ENEMY_FLARE_DANCER) && (has_bombs || can_use_mask_blast || can_hammer || can_hookshot) && has_weapon"
Added.

2025-01-12 17:48 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_LAVA_BRIDGE_ROOM_TORCHES: "has_fire" #Might need to separate intwo two events when action shuffle happens.
Yeah, but I put it there just in case.

2025-01-12 17:51 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon && (can_hookshot || climb_anywhere)" #You can get here to get to Upper Maze without the rusty switch.
Changed.

2025-01-12 17:59 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Maze Room Upper Switch Cage Alcove": "has_ranged_weapon"
Added the macro (copied from MM), and changed to what you wrote.

2025-01-12 18:04 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple 3F Lava Room Cage Area": "(has_tunic_goron && (is_adult || hookshot_anywhere || climb_anywhere)) || (has_tunic_goron_strict && can_hookshot)" #Adult can make an angled jump from the
Oh, okay. I will remove the comment then.

2025-01-12 18:32 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_3F_LAVA_ROOM_TORCHES: "event(FIRE_MQ_3F_LAVA_ROOM_BLUE_SWITCH) && can_use_bow" #I could not get fire arrows to hit; maybe it works though.
Made the change, and removed elegy.

2025-01-12 18:35 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_FLARE_DANCER_AFTER_FIRE_WALLS: "soul_enemy(SOUL_ENEMY_FLARE_DANCER) && (has_bombs || can_use_mask_blast || can_hammer || can_hookshot) && has_weapon"
Made the same change as before.

2025-01-12 18:47 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_TOWER_AFTER_FLARE_DANCER_CRYSTAL_SWITCH_FROM_BELOW: "event(FIRE_MQ_TOWER_TOP_HAMMER_SWITCH_BEFORE_STAIRCASE) && (has_ranged_weapon || has_bombchu)"
You are correct.

The need different events for *temporary* flags, not permanent ones. (Like the fire wall crystal switch in DC MQ boss loop)

IS this wrong though? Does it actually need to be changed?

2025-01-12 18:50 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && can_collect_distance"
Fixed.

2025-01-12 18:51 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (climb_anywhere || hookshot_anywhere)"
Because child can do it as well via the hookshot target jump. If both can do it free, no specification needed.

2025-01-12 18:52 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss": "has_tunic_goron && ((event(FIRE_MQ_PRE_BOSS_PILLAR) && has_hover_boots) || hookshot_anywhere || climb_anywhere)"
Because you said child can do it with hover boots regularly; if both can do it regularly, no age specification is needed.

2025-01-12 18:54 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS 1f Lava Room": "gs && can_damage_skull"
Fixed.

2025-01-12 18:57 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH: "trick(OOT_HAMMER_WALLS) && can_hammer"
I don't know where the comment about the unneeded region is so I can't cross-reference with that to understand the meaning of this anymore. Let's come back to it.

2025-01-12 19:11 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss": "has_tunic_goron && ((event(FIRE_MQ_PRE_BOSS_PILLAR) && has_hover_boots) || hookshot_anywhere || climb_anywhere)"
But now this forces hover boots to reach Volvagia.

2025-01-12 19:12 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (climb_anywhere || hookshot_anywhere)"
It still should just be the tunic though. If it can be done free, climb and hook anywhere are useless.

2025-01-12 19:25 UTC, XenoWars requested changes

2025-01-12 19:25 UTC, XenoWars commented on packages/data/src/macros/macros_oot.yml
> +"has_spin_upgrade": "cond(setting(sharedSpinUpgrade), has(SHARED_SPIN_UPGRADE), has(SPIN_UPGRADE))"
Oversight on my part. OOT can have the spin upgrade by just having magic without the spin upgrade item enabled, so would need slightly altered.

```suggestion
"has_spin_upgrade": "cond(setting(spinUpgradeOot), cond(setting(sharedSpinUpgrade), has(SHARED_SPIN_UPGRADE), has(SPIN_UPGRADE)), true)"
```

2025-01-12 19:25 UTC, XenoWars commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && (can_collect_distance || ((has_explosives || can_use_mask_blast || has_weapon || has_ranged_weapon) && climb_anywhere))"
Forgot to mention sticks would also work for climb anywhere.

2025-01-12 21:22 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss": "has_tunic_goron && ((event(FIRE_MQ_PRE_BOSS_PILLAR) && has_hover_boots) || hookshot_anywhere || climb_anywhere)"
Yes, to get from entrance side to pre-boss needs either climb/hook anywhere, or pillar+hovers.

Not added specifically for action shuffle, but it works for it.

Whenever I make sub-regions for a room, I always try to make logic to reach all of them, from each.

2025-01-12 21:24 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss Room Entrance Side": "has_tunic_goron && (climb_anywhere || hookshot_anywhere)"
You're right. Oversight on my part.

2025-01-12 21:26 UTC, Joshua8600 commented on packages/data/src/macros/macros_oot.yml
> +"has_spin_upgrade": "cond(setting(sharedSpinUpgrade), has(SHARED_SPIN_UPGRADE), has(SPIN_UPGRADE))"
Changed.

2025-01-12 21:27 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "MQ Fire Temple GS Topmost": "gs && (can_collect_distance || ((has_explosives || can_use_mask_blast || has_weapon || has_ranged_weapon) && climb_anywhere))"
Added.

2025-01-13 00:23 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Pre-Boss": "has_tunic_goron && ((event(FIRE_MQ_PRE_BOSS_PILLAR) && has_hover_boots) || hookshot_anywhere || climb_anywhere)"
Okay added adult or hovers

2025-01-13 00:31 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_MAZE_ROOM_LOWER_RUSTY_SWITCH: "trick(OOT_HAMMER_WALLS) && can_hammer"
Discussed on discord; resolved.

2025-01-13 00:52 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Fire Walls Middle Hallway Upper": "true"
Would require a rewrite of whole room. Added as a to-do.

2025-01-13 00:54 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    FIRE_MQ_PRE_BOSS_PILLAR: "can_hammer"
Updated for consistent logic with the ledge, added the TODO for new region

2025-01-13 00:55 UTC, Joshua8600 commented on packages/data/src/world/mq/fire_temple_mq.yml
> +    "Fire Temple Fire Walls Room Pillar Side": "event(FIRE_MQ_HIGH_LEDGE_AFTER_STAIRCASE_PILLAR)"
Added the TODO

2025-01-13 01:07 UTC, merged